print("Anna ensimmäinen numero")
arvo1 = input()
print("Anna toinen numero")
arvo2 = input()
summa = int(arvo1) + int(arvo2)
print("Numeroiden summa on:", summa)
erotus = int(arvo1) - int(arvo2)
print("Numeroiden erotus on:", erotus)
tulo = int(arvo1) * int(arvo2)
print("Numeroiden tulo on:", tulo)
osamaara = int(arvo1) / int(arvo2)
print("Numeroiden osamäärä on:", osamaara)